// Initialization
tr.prototype.init(['en','ru','ro'])
tr.prototype.set(localStorage.getItem('language'))
// Common
tr(['Orders','Заявки','Comenzi'])
tr(['Log out','Выход','Iesire'])
tr(['Cancel','Отмена',''])
tr(['Error','Ошибка',''])
// Page login
tr(['Log in','Вход','Intrare'])
tr(['Please log in to start working','Зарегистрируйтесь для начала работы',''])
tr(['Username','Имя пользователя',''])
tr(['Password','Пароль',''])
// Page main
tr(['Data loaded','Данные загружены',''])
tr(['Orders to upload','Заказов к отправке',''])
tr(['Orders uploaded','Отправлено заказов',''])
tr(['No data','Нет данных',''])
tr(['Current state','Текущее состояние',''])
tr(['Refresh','Обновить',''])
tr(['Upload','Отправить',''])
tr(['New order','Новый заказ',''])
tr(['Refresh database','Обновление базы данных',''])
tr(['Connection is in progress','Установка соединения',''])
tr(['Transaction success','Передача данных завершена',''])
tr(['Waiting time','Время ожидания',''])
tr(['sec.','сек.',''])
// Page setup
tr(['Current user','Текущий пользователь',''])
tr(['Change password','Сменить пароль',''])
tr(['Chosen language','Выбранный язык',''])
tr(['English','Английский','Engleza'])
tr(['Russian','Русский','Rusa'])
tr(['Romanian','Румынский','Romana'])
//
tr(['New document','Новый документ',''])
tr(['Documents','Документы',''])
tr(['Messages','Сообщения',''])
tr(['Clients','Клиенты',''])
tr(['Settings','Настройки',''])
tr(['Application not installed','Приложение не зарегистрировано',''])
tr(['Application installed','Приложение зарегистрировано',''])
tr(['Install','Зарегистрировать',''])
tr(['Uninstall','Отменить регистрацию',''])
tr(['Local data stored','Данные сохранены',''])
tr(['Local data not stored','Данные не сохранены',''])
tr(['Clear local storage','Очистить хранилище',''])
tr(['Store local data','Сохранить данные',''])
tr(['Enter a new password','Введите новый пароль',''])
tr(['Empty password is not allowed','Пароль не далжен быть пустым',''])
tr(['Entered passwords do not match','Введенные пароли не совпадают',''])
tr(['','',''])
