// Initialization
tr.prototype.init(['en','ru','ro'])
tr.prototype.set(localStorage.getItem('language'))
// Common
tr(['Orders','Заказы','Comenzi'])
tr(['Log out','Выход','Iesire'])
tr(['Cancel','Отмена',''])
tr(['Error','Ошибка',''])
// Page login
tr(['Log in','Вход','Intrare'])
tr(['Please log in to start working','Зарегистрируйтесь для начала работы',''])
tr(['Username','Имя пользователя',''])
tr(['Password','Пароль',''])
// Page main
tr(['Data loaded','Данные загружены',''])
tr(['Orders to export','Заказы к отправке',''])
tr(['Orders exported','Отправленные заказы',''])
tr(['Pre-Orders','Предзаказы',''])
tr(['No data','Нет данных',''])
tr(['Current state','Текущее состояние',''])
tr(['Refresh','Обновить',''])
tr(['Export','Отправить',''])
tr(['Order','Заказ',''])
tr(['New order','Новый заказ',''])
tr(['Export orders','Отправка заказов',''])
tr(['Refresh database','Обновление базы данных',''])
tr(['Connection is in progress','Установка соединения',''])
tr(['Transaction success','Передача данных завершена',''])
tr(['Network timeout limit','Макс. время ожидания',''])
tr(['Waiting time','Время ожидания',''])
tr(['sec.','сек.',''])
// Page setup
tr(['Current user','Текущий пользователь',''])
tr(['Current session','Текущая сессия',''])
tr(['Change password','Сменить пароль',''])
tr(['Chosen language','Выбранный язык',''])
tr(['English','Английский','Engleza'])
tr(['Russian','Русский','Rusa'])
tr(['Romanian','Румынский','Romana'])
// Reports
tr(['Reports','Отчеты','Rapoarte'])
tr(['Refresh report data','Обновление данных отчета',''])
tr(['Client Debts','Долги клиентов',''])
tr(['Sales Plans','Планы продаж',''])
//
tr(['Messages','Сообщения',''])
tr(['Routes','Маршруты',''])
tr(['Clients','Клиенты',''])
tr(['Products','Продукты',''])
tr(['Settings','Настройки',''])
tr(['Modify','Изменить',''])
tr(['Application not installed','Приложение не зарегистрировано',''])
tr(['Application installed','Приложение зарегистрировано',''])
tr(['Install','Зарегистрировать',''])
tr(['Uninstall','Отменить регистрацию',''])
tr(['Local data stored','Данные сохранены',''])
tr(['Local data not stored','Данные не сохранены',''])
tr(['Clear local storage','Очистить хранилище',''])
tr(['Store local data','Сохранить данные',''])
tr(['Enter a new password','Введите новый пароль',''])
tr(['Empty password is not allowed','Пароль не должен быть пустым',''])
tr(['Entered passwords do not match','Введенные пароли не совпадают',''])
tr(['','',''])
